name: Deploy Frontend

on:
  push:
    branches: ['main']

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      build-artifact: ${{ steps.my-artifact.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          path: './dist'
          if-no-files-found: error
          retention-days: 1
  ping-server:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Webhook
        uses: johannes-huther/webhook.sh@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"artifact-id": "${{ steps.my-artifact.outputs.artifact-id }}"}'
